on:
  push:
    branches:
      - main

name: Package

jobs:
  package:
    name: Package distribution files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install packages
        run: |
            npm ci
            npm install -g npm-check-updates

      - name: Package
        run: |
           export NODE_OPTIONS=--openssl-legacy-provider
           npm run package
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "Update dist" || echo "No changes to commit"
          git push origin main
